; // ==================================
; // component_ids.inc
; // ----------------------------------
; // A set of "enum" style macros that identify component types 
; // for the data definition and parsing of a scene's data.
; // ==================================

IFNDEF COMPONENT_IDS_INC
COMPONENT_IDS_INC EQU 1

; // List of component identifiers
RECT_COMPONENT = 0
SPRITE_COMPONENT = 1
TRANSFORM_COMPONENT = 2

ENDIF